---
title: "Week 12 - Data Analysis with R Shiny Apps"
author: "Tim Kelleman"
date: "2024-04-24"
output:
   
  html_document: 
    toc: no
    toc_depth: 4
    toc_float: yes
    fig_width: 8
    fig_caption: yes
    number_sections: yes
    toc_collapsed: yes
    code_folding: hide
    code_download: yes
    smooth_scroll: true
    theme: readable
  pdf_document: 
    toc: no
    toc_depth: 4
    fig_caption: yes
    number_sections: yes
    fig_width: 5
    fig_height: 4
runtime: shiny
---

```{=html}
<style type="text/css">

div#TOC li {
    list-style:none;
    background-color:lightgray;
    background-image:none;
    background-repeat:none;
    background-position:0;
    font-family: Arial, Helvetica, sans-serif;
    color: #780c0c;
}

/* mouse over link */
div#TOC a:hover {
  color: red;
}

/* unvisited link */
div#TOC a:link {
  color: blue;
}

h1.title {
  font-size: 24px;
  color: #3b6064;
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  font-variant-caps: normal;
}
h4.author { 
    font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: #364958;
  text-align: center;
}
h4.date { 
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: #3b6064;
  text-align: center;
}
h1 {
    font-size: 24px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: center;
}
h2 {
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h3 { 
    font-size: 15px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h4 { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: left;
}

/* unvisited link */
a:link {
  color: green;
}

/* visited link */
a:visited {
  color: green;
}

/* mouse over link */
a:hover {
  color: red;
}

/* selected link */
a:active {
  color: yellow;
}
</style>
```
---
```{r setup, include=FALSE}
# code chunk specifies whether the R code, warnings, and output 
# will be included in the output files.
options(repos = list(CRAN="http://cran.rstudio.com/"))
if (!require("knitr")) {
   install.packages("knitr")
   library(knitr)
}
if (!require("shiny")) {
   install.packages("shiny")
   library(shiny)
}
if (!require("ggplot2")) {
   install.packages("ggplot2")
   library(ggplot2)
}
if (!require("tidyverse")) {
   install.packages("tidyverse")
   library(tidyverse)
}
if (!require("dplyr")) {
   install.packages("dplyr")
   library(dplyr)
}
knitr::opts_chunk$set(echo = TRUE,       
                      warning = FALSE,   
                      result = TRUE,   
                      message = FALSE,
                      comment = NA)
```

```{r eval=TRUE}
library(shiny)

penguinData <- read.csv("https://tkelleman.github.io/tkweb/week3/w03-penguins.csv")
x.names = names(penguinData)[4:6]
y.names = names(penguinData)[4:6]

ui <- fluidPage(
  withMathJax(),
  tags$div(HTML("<script type='text/x-mathjax-config' >
            MathJax.Hub.Config({
            tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
            });
            </script >
            ")),
  br(), br(), 
  wellPanel(style = "background-color:#acdfe6;",
           titlePanel(h2("Analysis of Penguin Data", 
                align = "center",
                style = "color:#3b6064; 
                    font-family:verdana; 
                    font-variant: small-caps; 
                    font-weight: bold;")),
  ),
  sidebarLayout(
    sidebarPanel(style = "background-color:#acdfe6;",
                 tags$head(
                   tags$style("body {background-color:white }")  # 
                 ),
                 radioButtons(inputId = "species",
                              label = "Species",
                              choices = c("Adelie",
                                          "Gentoo",
                                          "Chinstrap",
                                          "All"),
                              inline = FALSE,
                              selected = "All"),
                 br(),
                 
                 selectInput(inputId = "Y",
                             label = "Response Variable: Y",
                             choices = y.names),
                 
                 selectInput(inputId = "X",
                             label =  "Predictor Variable: X",
                             choices = x.names,
                             selected = x.names[2]),
                 
                 sliderInput(inputId = "newX", 
                             label = "New Value for Prediction:", 
                             value = 2.5, 
                             min = 0, 
                             max = 20, 
                             step = 0.1),
                 hr(),
    ),   
    mainPanel(
      tabsetPanel(type = "tabs",
                  tabPanel(h5("Scatter Plot", style ="color:black; font-weight: bold;"), plotOutput("plot")),
                  tabPanel(h5("Regression Coefficients", style ="color:black; font-weight: bold;"), tableOutput("table")),
                  tabPanel(h5("Diagnostics", style ="color:black; font-weight: bold;"), plotOutput("diagnosis")),
                  tabPanel(h5("Prediction", style ="color:black; font-weight: bold;"), plotOutput("predPlt"))
      )
    )     
  )          
) 

## Server function
server <- function(input, output) {
  workDat = function(){
    if (input$species == "Adelie") {
      workingData = penguinData[which(penguinData$species == "Adelie"),]
    } else if (input$species == "Gentoo") {
      workingData = penguinData[which(penguinData$species == "Gentoo"),]
    } else if (input$species == "Chinstrap") {
      workingData = penguinData[which(penguinData$species == "Chinstrap"),]
    } else {
      workingData = penguinData
    }
    workingData 
  }
  ## Scatter Plot
  output$plot <- renderPlot({
    par(bg="#f4f3ee")
    dataset = workDat()[,-1]
    plot(dataset[,input$X], dataset[,input$Y], 
         xlab = input$X,
         ylab = input$Y,
         main = paste("Relationship between", input$Y, "and", input$X)
    )

    abline(lm(dataset[,input$Y] ~ dataset[,input$X]),
           col = "#e63946",
           lwd = 2)
  })
  ## Regression Coefficients
  output$table <- renderTable({
    br()
    br()
    dataset = workDat()[,-1]
    m0 = lm(dataset[,input$Y] ~ dataset[,input$X])
    regcoef = data.frame(coef(summary(m0)))
    regcoef$Pvalue = regcoef[,names(regcoef)[4]]
    regcoef$Variable = c("Intercept", input$X)
    regcoef[,c(6, 1:3, 5)]
    
  })
  
  ## Diagnostics
  output$diagnosis <- renderPlot({
    par(bg="#f4f3ee")
    dataset = workDat()[,-1]
    m1=lm(dataset[,input$Y] ~ dataset[,input$X])
    par(mfrow=c(2,2))
    plot(m1)
  })   
  
  ## Prediction
  output$predPlt <- renderPlot({
    par(bg="#f4f3ee")
    dataset = workDat()[,-1]
    m3 = lm(dataset[,input$Y] ~ dataset[,input$X])
    pred.y = coef(m3)[1] + coef(m3)[2]*input$newX
    plot(dataset[,input$X], dataset[,input$Y], 
         ylab = input$Y,
         xlab = input$X,
         main = paste("Relationship between", input$Y, "and", input$X)
    )
    abline(m3,
           col = "#e63946",
           lwd = 3,
           lty=2)
    points(input$newX, pred.y, pch = 19, col = "#e63946", cex = 2)
  })
}

shinyApp(ui = ui, server = server)
```